package com.seanshubin.vote.documentation

import com.seanshubin.vote.contract.EventLog
import com.seanshubin.vote.domain.DomainEvent
import kotlinx.datetime.Instant

class EventLogHtmlGenerator(private val eventLog: EventLog) {
    fun generate(): String = buildString {
        appendLine("<!DOCTYPE html>")
        appendLine("<html>")
        appendLine("<head>")
        appendLine("  <meta charset=\"UTF-8\">")
        appendLine("  <title>Event Log</title>")
        appendLine("  <style>")
        appendLine(css())
        appendLine("  </style>")
        appendLine("</head>")
        appendLine("<body>")
        appendLine("  <h1>Event Log</h1>")
        appendLine("  <p class=\"description\">Complete event sequence showing all domain events generated by the comprehensive scenario.</p>")
        appendLine("  <p class=\"description\">Event sourcing pattern: all state changes are captured as immutable events.</p>")
        appendLine()

        val events = eventLog.eventsToSync(0)

        appendLine("  <div class=\"stats\">")
        appendLine("    <div class=\"stat-box\">")
        appendLine("      <div class=\"stat-value\">${events.size}</div>")
        appendLine("      <div class=\"stat-label\">Total Events</div>")
        appendLine("    </div>")
        appendLine("    <div class=\"stat-box\">")
        appendLine("      <div class=\"stat-value\">${events.map { it.event::class.simpleName }.distinct().size}</div>")
        appendLine("      <div class=\"stat-label\">Event Types</div>")
        appendLine("    </div>")
        appendLine("  </div>")
        appendLine()

        appendLine("  <div class=\"events\">")
        for (envelope in events) {
            appendLine(generateEvent(envelope.eventId, envelope.authority, envelope.whenHappened, envelope.event))
        }
        appendLine("  </div>")

        appendLine("</body>")
        appendLine("</html>")
    }

    private fun generateEvent(eventId: Long, authority: String, whenOccurred: Instant, event: DomainEvent): String = buildString {
        val eventType = event::class.simpleName ?: "Unknown"
        val eventColor = getEventColor(eventType)

        appendLine("    <div class=\"event\">")
        appendLine("      <div class=\"event-header\">")
        appendLine("        <span class=\"event-id\">#$eventId</span>")
        appendLine("        <span class=\"event-type\" style=\"background-color: $eventColor;\">$eventType</span>")
        appendLine("        <span class=\"event-time\">$whenOccurred</span>")
        appendLine("        <span class=\"event-authority\">by $authority</span>")
        appendLine("      </div>")
        appendLine("      <div class=\"event-details\">")
        appendLine(formatEventDetails(event))
        appendLine("      </div>")
        appendLine("    </div>")
    }

    private fun formatEventDetails(event: DomainEvent): String = when (event) {
        is DomainEvent.UserRegistered -> """
            <div class="detail-row"><span class="label">User:</span> ${event.name}</div>
            <div class="detail-row"><span class="label">Email:</span> ${event.email}</div>
            <div class="detail-row"><span class="label">Role:</span> ${event.role}</div>
        """.trimIndent()
        is DomainEvent.UserEmailChanged -> """
            <div class="detail-row"><span class="label">User:</span> ${event.userName}</div>
            <div class="detail-row"><span class="label">New Email:</span> ${event.newEmail}</div>
        """.trimIndent()
        is DomainEvent.UserNameChanged -> """
            <div class="detail-row"><span class="label">Old Name:</span> ${event.oldUserName}</div>
            <div class="detail-row"><span class="label">New Name:</span> ${event.newUserName}</div>
        """.trimIndent()
        is DomainEvent.UserPasswordChanged -> """
            <div class="detail-row"><span class="label">User:</span> ${event.userName}</div>
            <div class="detail-row"><span class="label">Password:</span> (changed)</div>
        """.trimIndent()
        is DomainEvent.UserRoleChanged -> """
            <div class="detail-row"><span class="label">User:</span> ${event.userName}</div>
            <div class="detail-row"><span class="label">New Role:</span> ${event.newRole}</div>
        """.trimIndent()
        is DomainEvent.UserRemoved -> """
            <div class="detail-row"><span class="label">User:</span> ${event.userName}</div>
        """.trimIndent()
        is DomainEvent.ElectionCreated -> """
            <div class="detail-row"><span class="label">Owner:</span> ${event.ownerName}</div>
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
        """.trimIndent()
        is DomainEvent.ElectionUpdated -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            ${event.allowVote?.let { "<div class=\"detail-row\"><span class=\"label\">Allow Vote:</span> $it</div>" } ?: ""}
            ${event.allowEdit?.let { "<div class=\"detail-row\"><span class=\"label\">Allow Edit:</span> $it</div>" } ?: ""}
            ${event.secretBallot?.let { "<div class=\"detail-row\"><span class=\"label\">Secret Ballot:</span> $it</div>" } ?: ""}
        """.trimIndent()
        is DomainEvent.ElectionDeleted -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
        """.trimIndent()
        is DomainEvent.CandidatesAdded -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">Candidates:</span> ${event.candidateNames.joinToString(", ")}</div>
        """.trimIndent()
        is DomainEvent.CandidatesRemoved -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">Candidates:</span> ${event.candidateNames.joinToString(", ")}</div>
        """.trimIndent()
        is DomainEvent.VotersAdded -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">Voters:</span> ${event.voterNames.joinToString(", ")}</div>
        """.trimIndent()
        is DomainEvent.VotersRemoved -> """
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">Voters:</span> ${event.voterNames.joinToString(", ")}</div>
        """.trimIndent()
        is DomainEvent.BallotCast -> """
            <div class="detail-row"><span class="label">Voter:</span> ${event.voterName}</div>
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">Rankings:</span> ${event.rankings.joinToString(", ") { "${it.candidateName}:${it.rank}" }}</div>
            <div class="detail-row"><span class="label">Confirmation:</span> ${event.confirmation}</div>
        """.trimIndent()
        is DomainEvent.BallotTimestampUpdated -> """
            <div class="detail-row"><span class="label">Confirmation:</span> ${event.confirmation}</div>
            <div class="detail-row"><span class="label">New Timestamp:</span> ${event.newWhenCast}</div>
        """.trimIndent()
        is DomainEvent.BallotRankingsChanged -> """
            <div class="detail-row"><span class="label">Confirmation:</span> ${event.confirmation}</div>
            <div class="detail-row"><span class="label">Election:</span> ${event.electionName}</div>
            <div class="detail-row"><span class="label">New Rankings:</span> ${event.newRankings.joinToString(", ") { "${it.candidateName}:${it.rank}" }}</div>
        """.trimIndent()
    }

    private fun getEventColor(eventType: String): String = when {
        eventType.startsWith("User") -> "#3498db"
        eventType.startsWith("Election") -> "#9b59b6"
        eventType.startsWith("Candidate") -> "#e74c3c"
        eventType.startsWith("Voter") -> "#f39c12"
        eventType.startsWith("Ballot") -> "#2ecc71"
        else -> "#95a5a6"
    }

    private fun css() = """
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        h1 {
            color: #333;
            border-bottom: 3px solid #2ecc71;
            padding-bottom: 10px;
        }
        .description {
            color: #666;
            font-size: 14px;
            margin-bottom: 10px;
        }
        .stats {
            display: flex;
            gap: 20px;
            margin: 30px 0;
        }
        .stat-box {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
            flex: 1;
        }
        .stat-value {
            font-size: 36px;
            font-weight: bold;
            color: #2ecc71;
        }
        .stat-label {
            font-size: 14px;
            color: #666;
            margin-top: 5px;
        }
        .events {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }
        .event {
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .event-header {
            background: #ecf0f1;
            padding: 12px 15px;
            display: flex;
            align-items: center;
            gap: 10px;
            flex-wrap: wrap;
        }
        .event-id {
            font-weight: bold;
            color: #7f8c8d;
            font-family: monospace;
        }
        .event-type {
            padding: 4px 12px;
            border-radius: 12px;
            color: white;
            font-size: 13px;
            font-weight: 600;
        }
        .event-time {
            font-size: 12px;
            color: #7f8c8d;
            font-family: monospace;
        }
        .event-authority {
            font-size: 12px;
            color: #7f8c8d;
            font-style: italic;
            margin-left: auto;
        }
        .event-details {
            padding: 15px;
        }
        .detail-row {
            padding: 4px 0;
            font-size: 14px;
        }
        .label {
            font-weight: 600;
            color: #555;
            display: inline-block;
            min-width: 120px;
        }
    """.trimIndent()
}
